name: TestReader
on:
  workflow_dispatch:

env:
  CUSTOMER: CUSTOMER1

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MS_TOKEN: ${{ secrets.MS_TOKEN }} 
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        CLIENT_ID_1=env.CLIENT_ID
        
        echo "CLIENT_ID_1 = $CLIENT_ID_1"
        
        CLIENT_SECRET_1=${{ CLIENT_SECRET }}
        
        echo "CLIENT_SECRET_1 = $CLIENT_SECRET_1"
        
